import type {
  AggregateResponse,
  EndpointId,
  FinanceQuoteResponse,
  NewsResponse,
  UsageSummary,
  WeatherResponse,
} from "./types";

export const MOCK_API_KEY = "af_8a72c1d349b04f0c91e7b6d2a4e51c63";

export function mockWeather(city: string): WeatherResponse {
  return {
    city: capitalize(city),
    temperature_c: 18.4,
    humidity_pct: 62,
    condition: "Partly cloudy",
    wind_kph: 14.2,
    timestamp: new Date().toISOString(),
  };
}

export function mockNews(topic: string, limit = 5): NewsResponse {
  const articles = Array.from({ length: Math.min(limit, 5) }, (_, i) => ({
    title: `${capitalize(topic)} update #${i + 1}`,
    summary:
      "Demo article generated by the APIForge portal mock layer. Set NEXT_PUBLIC_APIFORGE_BASE_URL and use a real API key for live data.",
    source: ["TechCrunch", "Reuters", "The Verge", "Bloomberg", "Wired"][i % 5],
    url: `https://example.com/${topic}/${i + 1}`,
    published_at: new Date(Date.now() - i * 36e5).toISOString(),
  }));
  return { articles, total: articles.length, topic };
}

export function mockFinance(symbol: string): FinanceQuoteResponse {
  const upper = symbol.toUpperCase();
  return {
    symbol: upper,
    price: 187.42 + (upper.charCodeAt(0) % 20),
    change_pct: 1.34,
    volume: 12_345_678,
    market_cap: 2_900_000_000_000,
    timestamp: new Date().toISOString(),
  };
}

export function mockAggregate(city: string, topic: string): AggregateResponse {
  return {
    city,
    topic,
    weather: mockWeather(city),
    news: mockNews(topic),
    errors: {},
  };
}

export function mockRawUpstream(
  endpoint: EndpointId,
  params: Record<string, string>,
): { provider: string; url: string; body: unknown } {
  switch (endpoint) {
    case "weather":
      return {
        provider: "openweather",
        url: `https://api.openweathermap.org/data/2.5/weather?q=${params.city ?? "Berlin"}&units=metric`,
        body: {
          coord: { lon: 13.41, lat: 52.52 },
          weather: [{ id: 802, main: "Clouds", description: "scattered clouds" }],
          main: { temp: 18.4, humidity: 62 },
          wind: { speed: 3.94 },
          name: capitalize(params.city ?? "Berlin"),
          dt: Math.floor(Date.now() / 1000),
        },
      };
    case "news":
      return {
        provider: "newsapi",
        url: `https://newsapi.org/v2/everything?q=${params.topic ?? "ai"}&pageSize=${params.limit ?? "5"}`,
        body: {
          status: "ok",
          totalResults: 5,
          articles: mockNews(params.topic ?? "ai", Number(params.limit ?? 5)).articles.map((a) => ({
            source: { id: null, name: a.source },
            author: "demo",
            title: a.title,
            description: a.summary,
            url: a.url,
            publishedAt: a.published_at,
          })),
        },
      };
    case "finance":
      return {
        provider: "alphavantage",
        url: `https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${params.symbol ?? "AAPL"}`,
        body: {
          "Global Quote": {
            "01. symbol": (params.symbol ?? "AAPL").toUpperCase(),
            "05. price": "189.4200",
            "06. volume": "12345678",
            "10. change percent": "1.3400%",
          },
        },
      };
    case "aggregate":
      return {
        provider: "openweather + newsapi (parallel)",
        url: "asyncio.gather(weather, news)",
        body: {
          weather: mockRawUpstream("weather", { city: params.city ?? "Berlin" }).body,
          news: mockRawUpstream("news", { topic: params.topic ?? "ai", limit: "5" }).body,
        },
      };
  }
}

export function mockUsage(): UsageSummary {
  const now = new Date();
  const hourly = Array.from({ length: 24 }, (_, i) => {
    const d = new Date(now);
    d.setHours(now.getHours() - (23 - i), 0, 0, 0);
    const base = 8 + Math.sin(i / 2.5) * 6 + (i % 5);
    return {
      hour: `${d.getHours().toString().padStart(2, "0")}:00`,
      requests: Math.max(0, Math.round(base + Math.random() * 4)),
    };
  });
  const today = hourly.reduce((a, b) => a + b.requests, 0);
  const week = today * 6 + 42;

  const recent = Array.from({ length: 12 }, (_, i) => {
    const endpoints = [
      "/api/weather/Berlin",
      "/api/news?topic=ai&limit=5",
      "/api/finance/quote?symbol=AAPL",
      "/api/aggregate?city=Tokyo&topic=tech",
      "/api/weather/London",
    ];
    const statuses = [200, 200, 200, 200, 429, 200, 200, 502];
    const latency = [120, 240, 95, 410, 88, 670, 180, 145];
    return {
      id: `req_${i}`,
      endpoint: endpoints[i % endpoints.length],
      status: statuses[i % statuses.length],
      latency_ms: latency[i % latency.length] + (i % 3) * 25,
      timestamp: new Date(now.getTime() - i * 3 * 60 * 1000).toISOString(),
    };
  });

  return {
    today,
    week,
    hourly_limit: 100,
    remaining: Math.max(0, 100 - hourly[hourly.length - 1].requests),
    hourly,
    by_endpoint: [
      { endpoint: "/api/weather", requests: 142 },
      { endpoint: "/api/news", requests: 96 },
      { endpoint: "/api/finance", requests: 58 },
      { endpoint: "/api/aggregate", requests: 24 },
    ],
    recent,
  };
}

function capitalize(value: string): string {
  if (!value) return value;
  return value.charAt(0).toUpperCase() + value.slice(1);
}
